[messages]
welcome_message = "&aWelcome to the server!"
help_message = """&aCommands: login, log, l, lg, register, reg, zonezero help, zonezero reload, 2fa"""
please_register = "&aPlease register on server by using command '&b/register <password> <password>&a'"
please_login = "&aPlease login on server by using command '&b/login <password>&a'"
no_permission = "&cYou do not have permission to do this!"
insufficient_parameter = "&cYou must specify more parameters!"
redundant_parameter = "&cYou must specify fewer parameters!"
command_not_found = "&cCommand not found!"
reflection_error = "&cAn error occurred while executing the command!"
not_player = "&cYou cannot execute this command outside of the game!"
already_registered = "&cYou already registered!"
not_registered = "&cYou're not registered!"
plugin_restarted = "&aPlugin has been restarted"
error_on_restart = "&cAn error on plugin restart: <ERROR>"
already_logged_in = "&cYou're already logged in!"
successfully_logged_in = "&aYou have been logged in!"
successfully_logged_in_ip = "&aYou have been logged in by ip!"
successfully_registered = """&aYou have been registered!\nYou can now use /2fa"""
successfully_password_changed = "&aYour password has been changed!"
successfully_two_factor_enabled = "&a2Fa for your account has been enabled!"
successfully_two_factor_disabled = "&a2Fa for your account has been disabled!"
successfully_account_removed = "&a2Your account has been removed!"
two_factor_already_enabled = "&c2Fa already enabled on <EMAIL>!"
two_factor_already_disabled = "&c2Fa already disabled!"
two_factor_incorrect = "&c2Fa code is incorrect!"
wrong_password = "&cIncorrect password!"
password_mismatch = "&cThe entered passwords do not match!"
email_mismatch = "&cThe entered emails do not match!"
error_on_register = "&cError on register!"
error_on_login = "&cError on login!"
error_on_password_change = "&cError on password change!"
error_on_two_factor = "&cError on 2fa code (Serverside)!"
error_on_remove = "&cError on account remove (Serverside)!"
please_wait = "&aPlease wait..."
too_many_attempts = "&cToo many attempts. Please wait &f&l<SECONDS> &cseconds."
authorize_on_server = "&cPlease, authorize on server to do this!"
kick_unregistered = "&cYou are not registered in ZoneZero!"
two_factor_sent = "&aA two-step verification code has been sent to your email!"
two_factor_help = "HELP ABOUT 2FA"
not_email = "&cThis '<VALUE>' value is not an email!"
wrong_password_size = "&cPassword size cannot be less than <SIZE>!"
code_outdated = "&cYour code is outdated!"