[messages]
welcome_message = "&aWelcome to the server!"
help_message = """&aCommands: login, log, l, lg, register, reg, zonezero help, zonezero reload, 2fa"""
please_register = "&aPlease register on server by using command '&b/register <password> <password>&a'"
please_login = "&aPlease login on server by using command '&b/login <password>&a'"
no_permission = "&cYou do not have permission to do this!"
insufficient_parameter = "&cYou must specify more parameters!"
redundant_parameter = "&cYou must specify fewer parameters!"
command_not_found = "&cCommand not found!"
reflection_error = "&cAn error occurred while executing the command!"
not_player = "&cYou cannot execute this command outside of the game!"
already_registered = "&cYou already registered!"
not_registered = "&cYou're not registered!"
plugin_restarted = "&aPlugin has been restarted"
error_on_restart = "&cAn error on plugin restart: <ERROR>"
already_logged_in = "&cYou're already logged in!"
successfully_logged_in = "&aYou have been logged in!"
successfully_logged_in_ip = "&aYou have been logged in by ip!"
successfully_registered = """&aYou have been registered!\nYou can now use /2fa"""
successfully_password_changed = "&aYour password has been changed!"
successfully_two_factor_enabled = "&a2Fa for your account has been enabled!"
successfully_two_factor_disabled = "&a2Fa for your account has been disabled!"
successfully_account_removed = "&aYour account has been removed!\n&aPlease register on server by using command '&b/register <password> <password>&a'"
two_factor_already_enabled = "&c2Fa already enabled on <EMAIL>!"
two_factor_already_disabled = "&c2Fa already disabled!"
two_factor_incorrect = "&c2Fa code is incorrect!"
wrong_password = "&cIncorrect password!"
password_mismatch = "&cThe entered passwords do not match!"
email_mismatch = "&cThe entered emails do not match!"
error_on_register = "&cError on register!"
error_on_login = "&cError on login!"
error_on_password_change = "&cError on password change!"
error_on_two_factor = "&cError on 2fa code (Serverside)!"
error_on_remove = "&cError on account remove (Serverside)!"
please_wait = "&aPlease wait..."
too_many_attempts = "&cToo many attempts. Please wait &f&l<SECONDS> &cseconds."
authorize_on_server = "&cPlease, authorize on server to do this!"
kick_unregistered = "&cYou are not registered in ZoneZero!"
two_factor_sent = "&aA two-step verification code has been sent to your email!"
two_factor_help = "HELP ABOUT 2FA"
not_email = "&cThis '<VALUE>' value is not an email!"
wrong_password_size = "&cPassword size cannot be less than <SIZE>!"
code_outdated = "&cYour code is outdated!"

[titles]
title_welcome = "&fHey!"
title_login = "&6Please login"
title_register = "&cPlease register"
title_register_success = "&aSuccessful registration!"
title_error = "&cError!"
title_2fa_send = "&6Confirm action"
title_2fa_error = "&cConfirm error!"
title_2fa_success = "&aSuccess!"
title_password_wrong = "&cWrong password"
title_password_unsafe = "&cUnsafe password!"
title_password_mismatch = "&cPasswords not matches!"
title_email_mismatch = "&cEmails not matches!"
title_password_changed = "&6Password changed"

[subtitles]
subtitle_welcome = "&aWelcome back, &7<DISPLAY_NAME>&a!"
subtitle_login = "&7Login with &6/login <password>"
subtitle_register = "&7Register with &6/register <password> <password>"
subtitle_register_success = "&6You're registered. You can play now."
subtitle_error = "&7Please, check chat"
subtitle_2fa_send = "&72Fa code has been sent!"
subtitle_2fa_incorrect = "&72Fa code is incorrect!"
subtitle_2fa_expired = "&72Fa code is expired!"
subtitle_2fa_enabled = "&72Fa has been enabled"
subtitle_2fa_disabled = "&72Fa has been disabled"
subtitle_password_wrong = "&7Please, try again."
subtitle_password_unsafe = "&7Password must contain at least 8 characters"
subtitle_password_mismatch = "&7Password mismatch!"
subtitle_email_mismatch = "&7Email mismatch!"
subtitle_password_changed = "&7Your password has been changed!"