[messages]
welcome_message = "&aДобро пожаловать на сервер!"
help_message = """&aКоманды: login, log, l, lg, register, reg, zonezero help, zonezero reload, 2fa"""
please_register = "&aПожалуйста, зарегистрируйтесь на сервере используя команду '&b/register <password> <password>&a'"
please_login = "&aПожалуйста, авторизуйтесь на сервере используя команду '&b/login <password>&a'"
no_permission = "&cУ вас нет прав на это!"
insufficient_parameter = "&cВы должны указать больше параметров!"
redundant_parameter = "&cВы должны указать меньше параметров!"
command_not_found = "&cКоманда не найдена!"
reflection_error = "&cПроизошла ошибка во время выполнения команды!"
not_player = "&cВы не можете использовать эту команду не находясь на сервере!"
already_registered = "&cВы уже зарегистрированы!"
not_registered = "&cВы не зарегистрированы!"
plugin_restarted = "&aПлагин был перезагружен"
error_on_restart = "&cПроизошла ошибка во время перезагрузки плагина: <ERROR>"
already_logged_in = "&cВы уже вошли!"
successfully_logged_in = "&aВы вошли!"
successfully_logged_in_ip = "&aВы автоматически вошли на сервер по ip!"
successfully_registered = """&aВы были зарегистрированы!\nТеперь вы можете использовать /2fa"""
successfully_password_changed = "&aВаш пароль был изменён!"
successfully_two_factor_enabled = "&a2Fa для вашего аккаунта была включена!"
successfully_two_factor_disabled = "&a2Fa для вашего аккаунта была выключена!"
successfully_account_removed = "&a2Ваш аккаунт был удалён!"
two_factor_already_enabled = "&c2Fa уже активирована для почты <EMAIL>!"
two_factor_already_disabled = "&c2Fa уже отключена!"
two_factor_incorrect = "&c2Fa код неверный!"
wrong_password = "&cНеверный пароль!"
password_mismatch = "&cВведённые пароли не совпадают!"
email_mismatch = "&cВведённые почты не совпадают!"
error_on_register = "&cОшибка при регистрации!"
error_on_login = "&cОшибка при авторизации!"
error_on_password_change = "&cОшибка при смене пароля!"
error_on_two_factor = "&cОшибка при коде 2fa (На стороне сервера)!"
please_wait = "&aПожалуйста, подождите..."
too_many_attempts = "&cСлишком много попыток. Пожалуйста, подождите &f&l<SECONDS> &cсекунд."
authorize_on_server = "&cПожалуйста, авторизуйтесь на сервере!"
kick_unregistered = "&cВы не зарегистрированы в ZoneZero!"
two_factor_sent = "&aКод для подтверждения был выслан на вашу почту!"
two_factor_help = "ПОМОЩЬ О 2FA"
not_email = "&cДанное '<VALUE>' значение не является почтой!"
wrong_password_size = "&cДлина пароля <SIZE> не может быть меньше 8!"
code_outdated = "&cСрок службы вашего кода истёк!"