name: Build code
on:
  push:
    branches:
      - release
  workflow_dispatch:
    inputs:
      tags:
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Make gradlew executable again!
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Obfuscation with ProGuard
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: proguard
      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Builded jars
          path: 'build/proguard/*.jar'
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          nodetail: true
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: New version of `ZoneZero Auth`!
          description: |
            Version: `${{ github.event.head_commit.message }}`
            Click [here](https://www.spigotmc.org/resources/●-zonezero-unified-auth-system-alpha.108992/updates) to download!
          color: 0xFFD500
          username: ZoneZero Build
          avatar_url: ${{ secrets.AVATAR_URL }}
